### ISSUE TITLE
Needed Readme

### ISSUE THREAD

**Issue by Mr-Yash-beldar** [Mr-Yash-beldar/eJustIceBharat_Frontend#10]
- Need well structured Readme file related to Project

**Comment by PatilIsha** [comment]
Assign Me

**Comment by PatilIsha** [comment]
> * Need well structured Readme file related to Project
Assign Me

**Comment by Mr-Yash-beldar** [comment]
> > * Need well structured Readme file related to Project
> >   Assign Me

done
